### ISSUE TITLE
Fegaria will not launch

### ISSUE THREAD

**Issue by seth-stansberry** [FergusGriggs/Fegaria-Remastered#1]
Hey, I found your project on Pygame and went to run it because it looks cool- but I'm having trouble. In the current implementation there are no installation instructions for Fegaria-Remastered, so I went ahead and tried to install all the imports and launch it like that. But I ran into the hiccup of not being able to find the package `perlin` anywhere. I suggest adding some documentation to the README.md on how to install and launch your game.

```
~# easy_install perlin
Searching for perlin
Reading https://pypi.python.org/simple/perlin/
Couldn't find index page for 'perlin' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for perlin
error: Could not find suitable distribution for Requirement.parse('perlin')
```
Thanks,
Seth

**Comment by FergusGriggs** [comment]
Hey Seth, the 'perlin' module that the game uses does not need to be installed in any way, it is included in the files you download. If you just try running it and it should work.
